[package]
name = "helloworld"
version = "0.1.0"
authors = ["Jo Chuang <josephch405@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.6.0" }
specs = "0.15.0"
specs-derive = "0.4.0"
